<?php

// config/record_types.php — SALIN PENUH. Jenis medan: text|textarea|date|select|number|toggle
return [
    'surat_menyurat' => ['label' => 'Surat Menyurat', 'icon' => 'heroicon-o-envelope',
        'core' => ['direction*', 'our_ref', 'their_ref', 'record_date*', 'received_date', 'sender_name', 'sender_org', 'recipient_name'],
        'fields' => [
            ['name' => 'jumlah_lampiran', 'label' => 'Jumlah Lampiran', 'type' => 'number'],
            ['name' => 'untuk_perhatian', 'label' => 'Untuk Perhatian (u.p.)', 'type' => 'text'],
        ]],
    'memo' => ['label' => 'Memo', 'icon' => 'heroicon-o-document-text',
        'core' => ['our_ref', 'record_date*', 'sender_name*', 'recipient_name*'],
        'fields' => [['name' => 'jawatan_pengirim', 'label' => 'Jawatan Pengirim', 'type' => 'text']]],
    'emel' => ['label' => 'E-mel', 'icon' => 'heroicon-o-at-symbol',
        'core' => ['record_date*', 'sender_name*', 'recipient_name*'],
        'fields' => [
            ['name' => 'alamat_pengirim', 'label' => 'Alamat E-mel Pengirim', 'type' => 'text'],
            ['name' => 'cc', 'label' => 'CC', 'type' => 'text'],
            ['name' => 'subjek_asal', 'label' => 'Subjek Asal', 'type' => 'text'],
        ]],
    'emel_muatnaik' => ['label' => 'E-mel Muat Naik', 'icon' => 'heroicon-o-arrow-up-tray',
        'core' => ['record_date*', 'sender_name'],
        'fields' => [['name' => 'catatan_sumber', 'label' => 'Catatan Sumber', 'type' => 'text']]],
    'minit_mesyuarat' => ['label' => 'Minit Mesyuarat', 'icon' => 'heroicon-o-users',
        'core' => ['record_date*'],
        'fields' => [
            ['name' => 'nama_mesyuarat', 'label' => 'Nama Mesyuarat', 'type' => 'text', 'required' => true],
            ['name' => 'bilangan', 'label' => 'Bilangan (cth 3/2026)', 'type' => 'text'],
            ['name' => 'tempat', 'label' => 'Tempat', 'type' => 'text'],
            ['name' => 'pengerusi_mesyuarat', 'label' => 'Pengerusi Mesyuarat', 'type' => 'text'],
        ]],
    'laporan' => ['label' => 'Laporan', 'icon' => 'heroicon-o-chart-bar',
        'core' => ['record_date*', 'sender_name'],
        'fields' => [['name' => 'penyedia', 'label' => 'Penyedia', 'type' => 'text'],
            ['name' => 'tempoh_liputan', 'label' => 'Tempoh Liputan', 'type' => 'text']]],
    'kertas_kerja' => ['label' => 'Kertas Kerja / Konsep', 'icon' => 'heroicon-o-light-bulb',
        'core' => ['record_date*'],
        'fields' => [['name' => 'penyedia', 'label' => 'Penyedia', 'type' => 'text'],
            ['name' => 'anggaran_kos', 'label' => 'Anggaran Kos (RM)', 'type' => 'number']]],
    'borang' => ['label' => 'Borang', 'icon' => 'heroicon-o-clipboard-document-list',
        'core' => ['record_date', 'received_date', 'sender_name'],
        'fields' => [['name' => 'jenis_borang', 'label' => 'Jenis Borang', 'type' => 'text'],
            ['name' => 'no_borang', 'label' => 'No. Borang', 'type' => 'text']]],
    'tender_sebutharga' => ['label' => 'Dokumen Tender / Sebut Harga', 'icon' => 'heroicon-o-banknotes',
        'core' => ['record_date*', 'received_date', 'sender_org*'],
        'fields' => [
            ['name' => 'no_sebutharga', 'label' => 'No. Tender/Sebut Harga', 'type' => 'text', 'required' => true],
            ['name' => 'nilai', 'label' => 'Nilai Tawaran (RM)', 'type' => 'number'],
            ['name' => 'tarikh_tutup', 'label' => 'Tarikh Tutup', 'type' => 'date'],
        ]],
    'perjanjian' => ['label' => 'Perjanjian / Kontrak / MoU', 'icon' => 'heroicon-o-scale',
        'core' => ['record_date*', 'our_ref'],
        'fields' => [
            ['name' => 'pihak_terlibat', 'label' => 'Pihak-Pihak Terlibat', 'type' => 'textarea', 'required' => true],
            ['name' => 'tarikh_mula', 'label' => 'Tarikh Kuat Kuasa', 'type' => 'date'],
            ['name' => 'tarikh_tamat', 'label' => 'Tarikh Tamat', 'type' => 'date'],
            ['name' => 'nilai_kontrak', 'label' => 'Nilai (RM)', 'type' => 'number'],
            ['name' => 'lokasi_asal', 'label' => 'Lokasi Simpanan Salinan Asal Fizikal', 'type' => 'text', 'required' => true],
        ]],
    'pekeliling' => ['label' => 'Pekeliling', 'icon' => 'heroicon-o-megaphone',
        'core' => ['record_date*', 'received_date', 'sender_org', 'their_ref'],
        'fields' => [['name' => 'bilangan_tahun', 'label' => 'Bilangan/Tahun', 'type' => 'text'],
            ['name' => 'tarikh_kuatkuasa', 'label' => 'Tarikh Kuat Kuasa', 'type' => 'date']]],
    'garis_panduan' => ['label' => 'Garis Panduan', 'icon' => 'heroicon-o-book-open',
        'core' => ['record_date', 'sender_org'],
        'fields' => [['name' => 'versi', 'label' => 'Versi/Edisi', 'type' => 'text'],
            ['name' => 'penerbit', 'label' => 'Penerbit', 'type' => 'text']]],
    'jadual' => ['label' => 'Jadual', 'icon' => 'heroicon-o-calendar-days',
        'core' => ['record_date*'],
        'fields' => [['name' => 'tempoh', 'label' => 'Tempoh Jadual (cth Julai–Sep 2026)', 'type' => 'text']]],
    'poster' => ['label' => 'Poster / Hebahan', 'icon' => 'heroicon-o-photo',
        'core' => ['record_date*'],
        'fields' => [['name' => 'nama_program', 'label' => 'Nama Program', 'type' => 'text'],
            ['name' => 'tarikh_program', 'label' => 'Tarikh Program', 'type' => 'date'],
            ['name' => 'pereka', 'label' => 'Pereka', 'type' => 'text']]],
    'foto' => ['label' => 'Foto / Dokumentasi', 'icon' => 'heroicon-o-camera',
        'core' => ['record_date*'],
        'fields' => [['name' => 'nama_program', 'label' => 'Program/Peristiwa', 'type' => 'text', 'required' => true],
            ['name' => 'jurugambar', 'label' => 'Jurugambar', 'type' => 'text']]],
    'sijil' => ['label' => 'Sijil', 'icon' => 'heroicon-o-academic-cap',
        'core' => ['record_date*', 'sender_org'],
        'fields' => [['name' => 'penerima_sijil', 'label' => 'Penerima', 'type' => 'text'],
            ['name' => 'sah_hingga', 'label' => 'Sah Hingga', 'type' => 'date'],
            ['name' => 'lokasi_asal', 'label' => 'Lokasi Simpanan Salinan Asal', 'type' => 'text']]],
    'rekod_kewangan' => ['label' => 'Rekod Kewangan (Resit/Baucar)', 'icon' => 'heroicon-o-receipt-percent',
        'core' => ['record_date*', 'our_ref'],
        'fields' => [
            ['name' => 'jenis_dokumen', 'label' => 'Jenis', 'type' => 'select', 'options' => ['resit' => 'Resit', 'baucar' => 'Baucar Bayaran', 'invois' => 'Invois', 'penyata' => 'Penyata'], 'required' => true],
            ['name' => 'amaun', 'label' => 'Amaun (RM)', 'type' => 'number', 'required' => true],
            ['name' => 'pihak', 'label' => 'Dibayar Kepada / Diterima Daripada', 'type' => 'text', 'required' => true],
            ['name' => 'no_dokumen', 'label' => 'No. Resit/Baucar', 'type' => 'text'],
        ]],
];
// LARANGAN: jangan tambah medan no. kad pengenalan (§15.3).
